Add-most-populars
vsvldm/java-filmorate pull request #27
Opened 2024-04-16 16:37 UTC by MishailN1kolaev

2024-04-16 17:07 UTC, MaxGoodfella commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbStorage.java
> +    public Collection<Film> getPopularFilms(int count,Integer genreId,Integer year) {
Думаю, вот эти все if-ы лучше вынести на уровень сервиса. Но это оставляю на дальнейшее обсуждение пока.

2024-04-17 09:01 UTC, vsvldm commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbStorage.java
> +    public Collection<Film> getPopularFilms(int count,Integer genreId,Integer year) {
Я сделал все, что смог и кажется, что лучше уже не получается. Подключайся.

2024-04-17 10:29 UTC, MaxxMurygin requested changes

2024-04-17 10:29 UTC, MaxxMurygin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                       @RequestParam(required = false) Integer genreId,
Год и жанр - по ТЗ обязательные параметры.

2024-04-17 10:29 UTC, MaxxMurygin commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbStorage.java
> +        if (genreId != null || year != null) {
Параметры то обязательные =) Пиши один запрос, не грей голову =)

2024-04-17 11:18 UTC, vsvldm commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmDbStorage.java
> +        if (genreId != null || year != null) {
по постману не обязательные параметры

2024-04-17 13:01 UTC, MaxxMurygin approved these changes

2024-04-17 16:52 UTC, MaxGoodfella approved these changes

2024-04-17 16:54 UTC, merged